In [1]:
import sys, os, time
%load_ext autoreload
%autoreload 2
%matplotlib inline
#%matplotlib tk
import subprocess
import select
import numpy as np
import json
import yaml
import matplotlib.pyplot as plt
from collections import namedtuple, OrderedDict
import random
from string import Formatter
from itertools import chain, product
# import gsm
import gsm
from gsm import Savable
from gsm import tdict, tlist, tset, tstack, tdeque
from gsm import GameObject, GameLogger
from gsm.mixins import Named
from gsm import Array
from gsm import viz
from examples.tictactoe import TicTacToe
from gsm.common.world import grid
np.set_printoptions(linewidth=120)

/mnt/c/Users/anwan/Nextcloud/Khan/projects/gsm/git/gsm/io/registry.py:7: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  info = yaml.load(open(path, 'r'))


In [2]:
p = subprocess.Popen(['python', 'test_saving.py'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

In [17]:
poll_obj = select.poll()
poll_obj.register(p.stdout, select.POLLIN)   
while(some_criterium and not time_limit):
    poll_result = poll_obj.poll(0)
    if poll_result:
        line = scan_process.stdout.readline()
        some_criterium = do_something(line)
    update(time_limit)

In [15]:
# outs, errs = p.communicate()
# print(outs.decode(), end='')
print(p.stdout.readline().decode(), end='')
# print(p.stdout.readline().decode(), end='')

127.0.0.1 - - [01/Nov/2019 01:44:54] "POST /post HTTP/1.1" 200 -


In [7]:
print(p.stderr.readline().decode(), end='')

AttributeError: 'NoneType' object has no attribute 'readline'

In [5]:
gsm.send_msg('http://localhost:5000/', 'post', data=json.dumps({'test':'test'}))

'Request Processed.\n'

In [14]:
import subprocess
import shlex

In [18]:
command = shlex.split("ping -c 5 google.com")
process = subprocess.Popen(command, stdout=subprocess.PIPE)
output, err = process.communicate()

In [19]:
print(output.decode())

PING google.com (172.217.16.206) 56(84) bytes of data.
64 bytes from fra16s08-in-f206.1e100.net (172.217.16.206): icmp_seq=1 ttl=55 time=19.4 ms
64 bytes from fra16s08-in-f206.1e100.net (172.217.16.206): icmp_seq=2 ttl=55 time=16.9 ms
64 bytes from fra16s08-in-f206.1e100.net (172.217.16.206): icmp_seq=3 ttl=55 time=28.3 ms
64 bytes from fra16s08-in-f206.1e100.net (172.217.16.206): icmp_seq=4 ttl=55 time=21.3 ms
64 bytes from fra16s08-in-f206.1e100.net (172.217.16.206): icmp_seq=5 ttl=55 time=16.7 ms

--- google.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 3998ms
rtt min/avg/max/mdev = 16.703/20.535/28.326/4.254 ms



In [13]:
proc = subprocess.run(['python', 'test_saving.py'], capture_output=True)

KeyboardInterrupt: 

In [ ]:
print(proc.stdout.decode('utf-8'))

In [2]:
x = tdict(a=1, b=2, c=3, d=10)
x

tdict([('a', 1), ('b', 2), ('c', 3), ('d', 10)])

In [4]:
random.choices(*zip(*list(x.items())),k=10)

['d', 'd', 'b', 'c', 'd', 'd', 'c', 'b', 'd', 'a']

In [2]:
test_yaml = '../test_yaml.yaml'

In [ ]:
data = viz.unjsonify(yaml.load(open(test_yaml,'r'), Loader=yaml.SafeLoader))
data

tdict('map':['  W Y O  ', ' B S B O ', 'O S W Y S', ' D B Y W ', '  Y W S  '], 'field':tdict('W':tdict('res':'wood'), 'Y':tdict('res':'wheat'), 'S':tdict('res':'sheep'), 'O':tdict('res':'ore'), 'B':tdict('res':'brick'), 'D':tdict('res':'desert')))

In [4]:
M = data['map']
# M = ['A B', ' C ']

print('\n'.join(M))

  W Y O  
 B S B O 
O S W Y S
 D B Y W 
  Y W S  


In [5]:
G = grid.make_hexgrid(M, enable_corners=True, enable_edges=True)

In [6]:
G.keys()

odict_keys(['obj_type', 'fields', 'rows', 'cols', 'edges', 'corners'])

In [7]:
G.fields.keys()

odict_keys(['field0', 'field1', 'field2', 'field3', 'field4', 'field5', 'field6', 'field7', 'field8', 'field9', 'field10', 'field11', 'field12', 'field13', 'field14', 'field15', 'field16', 'field17', 'field18'])

In [8]:
str(G.fields.field0)

'tdict(obj_type, _id, row, col, neighbors, val, edges, corners)'

In [9]:
G.fields.field0.val

'W'

In [10]:
len(G.fields), len(G.corners), len(G.edges)

(19, 54, 72)

In [5]:
info = grid_util._create_grid(M, grid_type='hex',
              wrap_rows=False, wrap_cols=False,
#               enforce_connectivity=True,
              enable_edges=True, enable_corners=True, enable_boundary=False,
                )
info = viz.unjsonify(info)

In [6]:
info.keys()

odict_keys(['fields', 'map', 'edges', 'corners'])

In [7]:
info['fields'].keys()

odict_keys(['field0', 'field1', 'field2', 'field3', 'field4', 'field5', 'field6', 'field7', 'field8', 'field9', 'field10', 'field11', 'field12', 'field13', 'field14', 'field15', 'field16', 'field17', 'field18'])

In [8]:
print(info['map'])

[[None None 'field0' None 'field1' None 'field2' None None]
 [None 'field3' None 'field4' None 'field5' None 'field6' None]
 ['field7' None 'field8' None 'field9' None 'field10' None 'field11']
 [None 'field12' None 'field13' None 'field14' None 'field15' None]
 [None None 'field16' None 'field17' None 'field18' None None]]


In [9]:
len(info.fields), len(info.edges), len(info.corners)

(19, 72, 54)

In [2]:
class Test(object):
    def __new__(cls, *args, **kwargs):
        print('__new__', args, kwargs)
        return super().__new__(cls)
    def __init__(self, *args, **kwargs):
        super().__init__()
        print('__init__', args, kwargs)

In [3]:
a = Test()

__new__ () {}
__init__ () {}


In [4]:
b = Test.__new__(Test)
b.__init__()

__new__ () {}
__init__ () {}


In [5]:
a, b

(<__main__.Test at 0x7f7dfc193320>, <__main__.Test at 0x7f7dfc1dc390>)

In [6]:
dir(a) == dir(b)

True

In [5]:
def f(*args):
    print(type(args))
    print(args)

In [21]:
f({}, 'a', **Test())

__new__ () {}
__init__ () {}


TypeError: f() argument after ** must be a mapping, not Test

In [11]:
([1,2],{'z','x'}) == ([1,2],{'z','x'})

True

In [14]:
{'z','x'} == {'x','z', 'y'}

False

In [15]:
class Test:
    def __init__(self, x=1):
        super().__init__()
        self.val = x
    def __str__(self):
        return 'TEST({})'.format(self.val)
    def __repr__(self):
        return 'Test({})'.format(self.val)
    def __eq__(self, other):
        try:
            return self.val == other.val
        except AttributeError:
            return self.val == other

    def __add__(self, other):
        try:
            return self.val + other.val
        except AttributeError:
            return self.val + other

In [16]:
a = np.array([[Test(),Test(), Test()], [Test(),Test(), Test()]])
a

array([[Test(1), Test(1), Test(1)],
       [Test(1), Test(1), Test(1)]], dtype=object)

In [20]:
a[1,2] += 1

In [23]:
np.arange(3)[[False, False, False]]

array([], dtype=int64)

In [22]:
a.sum(0)

array([2, 2, 3], dtype=object)

In [9]:
a.dtype.name

'object'

In [10]:
np.array(a.tolist(), dtype='object')

array([[Test(1), Test(1), Test(1)],
       [Test(1), Test(1), Test(1)]], dtype=object)

In [14]:
a = np.empty((3,3), dtype='object')
a

array([[None, None, None],
       [None, None, None],
       [None, None, None]], dtype=object)

In [31]:
x = a.tolist()
x

[[Test(1), Test(1)], [Test(1), Test(1)]]

In [2]:
G = make_quadgrid(3,3)
G.keys()

odict_keys(['obj_type', 'fields'])

In [4]:
G.fields.keys()

odict_keys(['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9'])

In [11]:
G = grid.quadgrid(3,3)

[autoreload of gsm.wrappers failed: Traceback (most recent call last):
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 246, in check
    superreload(m, reload, self.old_objects)
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 369, in superreload
    module = reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/anwan/OneDrive - UW Office 365/Khan/Other/gsm/git/gsm/wrappers.py", line 11, in <module>
    class ObjectWrapper(ObjectProxy, Transactionable, Savable):
  File "

In [12]:
viz.render_dict(G)

In [13]:
int('')

ValueError: invalid literal for int() with base 10: ''

In [11]:
gen = random.Random(1)

In [12]:
gen.random()
gen.random()

0.8474337369372327

In [13]:
g1 = random.Random()
g1.setstate(gen.getstate())
g1.random()

[autoreload of gsm.util failed: Traceback (most recent call last):
  File "/home/fleeb/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/home/fleeb/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 368, in superreload
    module = reload(module)
  File "/home/fleeb/anaconda3/lib/python3.7/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/home/fleeb/anaconda3/lib/python3.7/importlib/__init__.py", line 160, in reload
    name=parent_name) from None
ImportError: parent 'gsm' not in sys.modules
]


0.763774618976614

In [80]:
hex(gen.getrandbits(64))

'0x81f9c1f66c0f3459'

In [19]:
gen._shadow

[autoreload of gsm.util failed: Traceback (most recent call last):
  File "/home/fleeb/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/home/fleeb/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 368, in superreload
    module = reload(module)
  File "/home/fleeb/anaconda3/lib/python3.7/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/home/fleeb/anaconda3/lib/python3.7/importlib/__init__.py", line 160, in reload
    name=parent_name) from None
ImportError: parent 'gsm' not in sys.modules
]


AttributeError: 'Random' object has no attribute '_shadow'

In [14]:
gen.random()

0.763774618976614

In [7]:
gen.random()

0.8474337369372327

In [15]:
gen.getstate()

[autoreload of gsm.util failed: Traceback (most recent call last):
  File "/home/fleeb/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/home/fleeb/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py", line 368, in superreload
    module = reload(module)
  File "/home/fleeb/anaconda3/lib/python3.7/imp.py", line 314, in reload
    return importlib.reload(module)
  File "/home/fleeb/anaconda3/lib/python3.7/importlib/__init__.py", line 160, in reload
    name=parent_name) from None
ImportError: parent 'gsm' not in sys.modules
]


(3,
 (2145931878,
  2812664348,
  2124062512,
  3757238068,
  2453315318,
  1634707757,
  1382563816,
  2097433739,
  311746133,
  2032626074,
  2617776101,
  1877538630,
  1158287594,
  1111761113,
  650853131,
  3869983018,
  2622923993,
  3845947563,
  4034124803,
  3529923841,
  263419425,
  988778765,
  459585442,
  250000960,
  2862328889,
  3831024473,
  376081109,
  3160276335,
  2681558278,
  3610562257,
  3737464566,
  4277502420,
  810823568,
  1660136801,
  3616377324,
  3405043087,
  312580666,
  3533264489,
  1350493301,
  2122280547,
  3694157202,
  4101260871,
  334760505,
  1001399085,
  4032193053,
  635051900,
  1014848001,
  77323629,
  1070905620,
  4245065876,
  197191146,
  2668164234,
  2624765451,
  3263880227,
  1253021119,
  780557860,
  3494191106,
  1888043228,
  2730480597,
  2457734185,
  533240640,
  3054437375,
  2913464164,
  1357763286,
  1045027602,
  1724499345,
  3008672616,
  3438668475,
  3323437141,
  2773702905,
  747342820,
  346050065,
  2381

In [2]:
x = np.random.randn(3)
x

array([-0.34398902, -0.84450839, -1.56259909])

In [3]:
# Savable._Savable__subclasses.keys()

In [4]:
a = Array(np.zeros(3))
a

__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_ipython_display_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_mimebundle_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
__wrapped__
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_html_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_markdown_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_svg_
__class__
callable <class 'numpy.ndarray'>
__class__
callable <class 'numpy.ndarray'>
_ipython_canary_method_should_not_exist_
_repr_png_
__class__
callable <class 'numpy.ndarray'>
__class__
c

array([ 0.,  0.,  0.])

In [5]:
type(a)

gsm.wrappers.Array

In [6]:
b = a+1
b, type(b)

(array([ 1.,  1.,  1.]), numpy.ndarray)

In [11]:
type(a.__add__(1))

__add__
callable <method-wrapper '__add__' of Array object at 0x7fb2fa938088>


numpy.ndarray

In [12]:
type(a.__add__)

__add__
callable <method-wrapper '__add__' of Array object at 0x7fb2fa938088>


method-wrapper

In [7]:
type(a.__wrapped__)

__wrapped__


numpy.ndarray

In [5]:
dir(np.ndarray)

[autoreload of gsm.wrappers failed: Traceback (most recent call last):
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 246, in check
    superreload(m, reload, self.old_objects)
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 369, in superreload
    module = reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/anwan/OneDrive - UW Office 365/Khan/Other/gsm/git/gsm/wrappers.py", line 10, in <module>
    class ObjectWrapper(ObjectProxy, Transactionable, Savable):
  File "

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [19]:
from wrapt import ObjectProxy
import numpy as np

class A(ObjectProxy):
    
    def __init__(self, a):
        super().__init__(a)
        
    def __save(self):
        print('saved')
        
    
    def __load(self, a):
        
        super().__init__(a)
        print('load')
        
    def __repr__(self):
        return self.__wrapped__.__repr__()
    
    @staticmethod
    def loadx(obj, data):
        obj.__init__(data)
    
    def __getattribute__(self, item):
        print(item)
        return super().__getattribute__(item)

In [20]:
a = A(np.zeros(10))
a

__class__
__class__
_ipython_canary_method_should_not_exist_
_ipython_display_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_mimebundle_
__class__
__class__
__wrapped__
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_html_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_markdown_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_svg_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_png_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_pdf_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_jpeg_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_latex_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_json_
__class__
__class__
_ipython_canary_method_should_not_exist_
_repr_javascript_


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [18]:
b = A.__new__(A)
b.load(np.zeros(10))
b

__load


ValueError: wrapper has not been initialized

In [7]:
a += 1
type(a)

__main__.A

In [8]:
a.__wrapped__

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [3]:
x = tdict()
x

tdict()

In [3]:
p = Savable.create('gsm.util.Player')
p.x = 'x'
p.x

'x'

In [4]:
p

Player([('x', 'x')])

In [5]:
class Test(object):
    
    __m = 'm'
    
    def __new__(cls, *args, **kwargs):
        print(args, kwargs)
        return super().__new__(cls)
    
    def __init__(self, x):
        self.__x = x
        self.__dict__['__y'] = x+1
        
    def f(self):
        print(self.__x)
        print(self.__y)
        
    def __setattr__(self, x, y):
        print(x, y)
        super().__setattr__(x,y)
        
class T2(Test):
    def f(self, x):
        print(self, x)
    
    def g(self, x):
        print(x)

In [6]:
dir(t)

NameError: name 't' is not defined

In [7]:
t = Test(1)

(1,) {}
_Test__x 1


In [1]:
import time

In [5]:
time.strftime('%Y-%m-%d_%H%M%S')

'2019-09-17_135729'

In [9]:
Test._Test__m

'm'

In [27]:
t.__dict__

{'_Test__x': 1, '__y': 2}

In [29]:
t.__y

2

In [28]:
t.f()

1


AttributeError: 'Test' object has no attribute '_Test__y'

In [13]:
# class Sup(object):
#     @classmethod 
#     def makeit(cls):
#         self = cls.__new__(cls)
#         # etc etc, then
#         return self

class Test(object):
    
    def __init__(self, x):
        super().__init__()
        print(x)
        self.x = x
    
    def f(self):
        print(self.x)

In [14]:
a = Test()

TypeError: __init__() missing 1 required positional argument: 'x'

In [15]:
a = Test.__new__(Test)
a.f()

AttributeError: 'Test' object has no attribute 'x'

In [10]:
m = np.zeros((3,3), dtype=int)
m[0,0]= 1
m[1,1] = -1
m

array([[ 1,  0,  0],
       [ 0, -1,  0],
       [ 0,  0,  0]])

In [11]:
json.loads(json.dumps({'x':1.245}))

{'x': 1.245}

In [6]:
np.array([1,2]).__getstate__()

AttributeError: 'numpy.ndarray' object has no attribute '__getstate__'

In [2]:
int('a')

ValueError: invalid literal for int() with base 10: 'a'

In [13]:
Test()

TypeError: __init__() missing 1 required positional argument: 'x'

In [12]:
x, y = np.mgrid[0:m.shape[0],0:m.shape[1]]

In [1]:
class Test(object):
    
    def __init__(self, x):
        print('init', x)
    
    def __init_subclass__(cls, **kwargs):
        print(cls)
        print(kwargs)
    
    def __new__(self, x):
        print('new', x)
        super().__new__(self)

In [6]:
Test(1)

new 1


In [2]:
class T2(object):
    pass

class T1(Test, T2):
    def __init__(self, x):
        super().__init__(x)
        print(x+1)

<class '__main__.T1'>
{}


In [ ]:
'test'.__getstate__()

In [4]:
type('a')(1)

[autoreload of gsm.core.actions failed: Traceback (most recent call last):
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 246, in check
    superreload(m, reload, self.old_objects)
  File "/home/fleeb/anaconda3/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 369, in superreload
    module = reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/fleeb/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/c/Users/anwan/One

'1'

In [13]:
s = 'test {} {{a {:3.2f} b {:} c {p[x]:} d'
s.format('A', 1234.2351, 'B', p={'x':'X'})

'test A {a 1234.24 b B c X d'

In [14]:
F = Formatter()
list(F.parse(s))

[('test ', '', '', None),
 (' {', None, None, None),
 ('a ', '', '3.2f', None),
 (' b ', '', '', None),
 (' c ', 'p[x]', '', None),
 (' d', None, None, None)]

In [15]:
'test'.__class__.__name__

'str'

In [2]:
class Parent:
    def signal(self):
        print('bing')

In [3]:
a = tdict(a=10, c='hello', _tracker=Parent())
a._tracker = Parent()
a

tdict('a':10, 'c':'hello')

In [4]:
a.begin()

In [5]:
a.a = 11
a.b = tdict()
a.d = 'testing'
a.b.deep = 'yes'
a

bing
bing
bing
bing


tdict('a':11, 'c':'hello', 'b':tdict('deep':'yes'), 'd':'testing')

In [6]:
a.abort()
a

tdict('a':10, 'c':'hello')

In [7]:
a._tracker

In [7]:
a = tlist([tdict(x=1), tdict(ad=3)], _tracker=Parent())
a

bing


[tdict('x':1), tdict('ad':3)]

In [9]:
a.begin()
a.append('x')
a

bing


[tdict('x':1), tdict('ad':3), 'x']

In [10]:
# a.add(tdict())
for x in a:
#     print(x)
    try:
        x.v = 14
    except Exception as e:
        print('pass',x)
#         raise e
        pass
a

bing
bing
pass x


[tdict('x':1, 'v':14), tdict('ad':3, 'v':14), 'x']

In [12]:
a.abort()
a

[tdict('x':1), tdict('ad':3)]